spring:
  application:
    name: customer-service
  data:
    mongodb:
      password: mongo
      username: mongo
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090